### ISSUE TITLE
home_run-1.0.3/lib/date_ext.so: [BUG] Segmentation fault

### ISSUE THREAD

**Issue by chase439** [jeremyevans/home_run#33]
I ran "home_run --install" after installing home_run gem. 
running "home_run rake test" produced: 

<pre>
/home/chase/.rvm/gems/ree-1.8.7-2011.03@myapp/gems/home_run-1.0.3/lib/date_ext.so: [BUG] Segmentation fault
ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-linux], MBARI 0x8770, Ruby Enterprise Edition 2011.03
</pre>

Could you please assist? My software versions are below.

[chase@ChaseFedora myapp]$ uname -a
Linux ChaseFedora 2.6.38.8-35.fc15.i686
[chase@ChaseFedora myapp]$ ruby -v
ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-linux], MBARI 0x8770, Ruby Enterprise Edition 2011.03
[chase@ChaseFedora myapp]$ rails -v

<pre>/home/chase/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/site_ruby/1.8/i686-linux/date_ext.so: [BUG] Segmentation fault
ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-linux], MBARI 0x8770, Ruby Enterprise Edition 2011.03

Aborted (core dumped)
</pre>

[chase@ChaseFedora myapp]$ rvm -v
rvm 1.6.31 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]

**Comment by jeremyevans** [comment]
A few things you can try:

1) Run it on MRI 1.8.7 or 1.9.2 (to rule out issues caused by REE).

2) If you still get a segfault on MRI, use gdb to get a backtrace and send it in (gdb ruby ruby.core; bt).  Even better if you can built a debug version of home_run (set DEBUG=1 in your environment when doing gem install) and ruby (set CFLAGS="-g" in your environment when building ruby).

**Comment by chase439** [comment]
I did not get seg fault on MRI, but got the following:

<pre>
[chase@ChaseFedora myapp]$ ruby -v
ruby 1.9.2p290 (2011-07-09 revision 32553) [i686-linux]
[chase@ChaseFedora myapp]$ home_run rake test --trace
rake aborted!
undefined method `+' for class `Date'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.0.9/lib/active_support/core_ext/date/calculations.rb:91:in `alias_method'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.0.9/lib/active_support/core_ext/date/calculations.rb:91:in `<class:Date>'
...
...
</pre>


is this a problem with my app?

---

Here's the email communication previously with Jeremy in case someone else is having same problems:

> Hi Jeremy,
> 
> I saw your response. However, i'm fairly new to Ruby environment and could
> use more help. Could you provide more detailed instructions on how to run
> troubleshooting item #2, perhaps a link of understanding how to debug stuff?
> After I got the seg fault, I ran (gdb ruby ruby.core; and then "bt"), but it
> returned no stack. Specifically, I don't know how to set those variables for
> dedug.

Usually a "no stack" message means that something has messed with the
program stack.  It's unlikely that home_run has done this, but it's
possible it does on REE as I never tested it there.  Did you try on MRI
1.8.7 or 1.9.2?

Also, instead of using home_run, you could try ruby 1.9.3 preview 1, as
it includes a new stdlib date library that is more compatible than
home_run and almost as fast.

As for building a debug version of home run:

DEBUG=1 gem install home_run

building a debug version of ruby:

CPPFLAGS=-g ./configure
make
make install

Also, in the future you should probably just respond on GitHub so that
everyone can benefit from the answer.

Jeremy

**Comment by jeremyevans** [comment]
It probably isn't a problem with your app.  It may be a bug in ActiveSupport that's fixed in head but they didn't backport to 3.0-stable.

**Comment by chase439** [comment]
Yup I updated to the latest activesupport gem and still experienced same error:

<pre>
[chase@ChaseFedora myapp]$ gem list activesupport*
*** LOCAL GEMS ***
activesupport (3.0.9)
[chase@ChaseFedora myapp]$ home_run rake test --trace
rake aborted!
undefined method `+' for class `Date'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.0.9/lib/active_support/core_ext/date/calculations.rb:91:in `alias_method'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.0.9/lib/active_support/core_ext/date/calculations.rb:91:in `&lt;class:Date>'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.0.9/lib/active_support/core_ext/date/calculations.rb:7:in `&lt;top (required)>'
</pre>

**Comment by jeremyevans** [comment]
Like my previous message said, they didn't backport the fix to 3.0-stable.  You could try a 3.1 release candidate and see if it's fixed there.

**Comment by chase439** [comment]
testing it with http://rubygems.org/gems/rails/versions/3.1.0.rc5 ... having a bit of problem with bundler. Will get back to you soon.

**Comment by chase439** [comment]
Sorry about the late follow up.
FYI: It's still not working. I will try to contact an owner of the rails gem.

Tried rails 3.0.10.rc1

<pre>
$ bundle exec rake about --trace
rake aborted!
undefined method `+' for class `Date'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.0.10.rc1/lib/active_support/core_ext/date/calculations.rb:91:in `alias_method'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.0.10.rc1/lib/active_support/core_ext/date/calculations.rb:91:in `&lt;class:Date>'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.0.10.rc1/lib/active_support/core_ext/date/calculations.rb:7:in `&lt;top (required)>'
</pre>


Tried rails 3.1.0.rc5 

<pre>
$ bundle exec rake about --trace
rake aborted!
undefined method `+' for class `Date'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.1.0.rc5/lib/active_support/core_ext/date/calculations.rb:93:in `alias_method'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.1.0.rc5/lib/active_support/core_ext/date/calculations.rb:93:in `&lt;class:Date>'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.1.0.rc5/lib/active_support/core_ext/date/calculations.rb:7:in `&lt;top (required)>'
</pre>

**Comment by jeremyevans** [comment]
Did you use `home_run --install`?  What's the result of `home_run bundle exec rake about --trace` or `bundle exec home_run rake about --trace`?

**Comment by chase439** [comment]
Jeremy, here are the results of those commands:

<pre>
[chase@ChaseFedora myapp]$ home_run --install
cp lib/date.rb /home/chase/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1
mkdir -p /home/chase/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/date
cp lib/date/format.rb /home/chase/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/date
cp lib/date_ext.so /home/chase/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/i686-linux

[chase@ChaseFedora myapp]$ home_run bundle exec rake about --trace
rake aborted!
undefined method `+' for class `Date'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.1.0.rc5/lib/active_support/core_ext/date/calculations.rb:93:in `alias_method'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.1.0.rc5/lib/active_support/core_ext/date/calculations.rb:93:in `&lt;class:Date>'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.1.0.rc5/lib/active_support/core_ext/date/calculations.rb:7:in `&lt;top (required)>'

[chase@ChaseFedora myapp]$ bundle exec home_run rake about --trace
rake aborted!
undefined method `+' for class `Date'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.1.0.rc5/lib/active_support/core_ext/date/calculations.rb:93:in `alias_method'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.1.0.rc5/lib/active_support/core_ext/date/calculations.rb:93:in `&lt;class:Date>'
/home/chase/Desktop/apps_rails/myapp/rails/ruby/1.9.1/gems/activesupport-3.1.0.rc5/lib/active_support/core_ext/date/calculations.rb:7:in `&lt;top (required)>'
</pre>

**Comment by jeremyevans** [comment]
Very weird.  Only thing I can think of now is a problem with your Gemfile.  Do you have it setup as mentioned in the README: `gem 'home_run', :require=>'date'`?  If you already have that, can you provide a link to the app so that I can test it?

**Comment by chase439** [comment]
Yes, I have that exactly in my Gemfile. Since my app is a private project, I'll send you an email with the link.

**Comment by chase439** [comment]
You gave me a great tip on the email. I tried to create a new app to use the same Gemfile. I had to modify Gemfile to use the following to fix some errors:

<pre>
gem 'rails', '3.0.9'
gem 'mongrel', "~> 1.2.0.pre2"
</pre>

Ran "bundle install", then the rake and home_run commands I ran before worked. Then I copied that same Gemfile back to my original app, ran "rvm use 1.9.2" since my app defaulted to REE, deleted Gemfile.lock, ran "bundle install". Then the commands worked there too! FYI: I found that reading all of http://gembundler.com/man/bundle-update.1.html was helpful on understanding how bundler works. 

Now, that things work using ruby 1.9.2 (didn't need the latest rails - 3.1 release candidate), I find that it still core dumps when using REE 1.8.7. Will find a way to resolve this, or wait until next REE update.

Thank you for your patience and help, Jeremy! Much appreciated!

**Comment by chase439** [comment]
FYI: Just found that the undefined method errors occur, even in ruby 1.9.2, when config/application.rb has the following at the top of the file:

<pre>
require File.expand_path('../boot', __FILE__)
require 'home_run'
require 'rails/all'
</pre>

Error, like "undefined method '+' for class `Date'" occurs when I ran "rake about". It works fine when I commented out "require 'home_run'".

**Comment by chase439** [comment]
It also works fine after I swapped the order in config/application.rb to: 

<pre>
require File.expand_path('../boot', __FILE__)
require 'rails/all'
require 'home_run'
</pre>

So I believe this was the main problem & solution to running it on ruby 1.9.2.

**Comment by jeremyevans** [comment]
You shouldn't `require 'home_run'` except as a last resort, as explained in the README.  If you `require 'home_run'` after rails/all, you can end up with problems later even if rake about doesn't bring up any errors.

Anyway, I'm glad this issue got resolved. :)
