### ISSUE TITLE
unable to get working with rails 3.0.7

### ISSUE THREAD

**Issue by inspire22** [jeremyevans/home_run#27]
I had an old version at first, but tried reinstalling:
    newap ➤ brew install ragel  
    ==> Downloading http://www.complang.org/ragel/ragel-6.6.tar.gz
    ######################################################################## 100.0%
    ==> ./configure --disable-dependency-tracking --prefix=/usr/local/Cellar/ragel/6.6
    ==> make install
    /usr/local/Cellar/ragel/6.6: 9 files, 2.5M, built in 60 seconds
    newap ➤ gem install home_run  
    Fetching: home_run-1.0.2.gem (100%)
    Building native extensions.  This could take a while...
    Successfully installed home_run-1.0.2
    1 gem installed
    newap ➤ home_run --install  
    cp lib/date.rb /Users/inspire/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/site_ruby/1.8
    mkdir -p /Users/inspire/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/site_ruby/1.8/date
    cp lib/date/format.rb /Users/inspire/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/site_ruby/1.8/date
    cp lib/date_ext.bundle /Users/inspire/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/site_ruby/1.8/i686-darwin10.7.0
    newap ➤ cd lib  
    lib ➤ ruby benchmarks.rb  
    Starting new rails
    /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/home_run-1.0.0/lib/date/format.rb:663:in `_parse': undefined method`_ragel_parse' for Date:Class (NoMethodError)

with home_run --install:

```
/Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/home_run-1.0.2/lib/date/format.rb:663:in `_parse': undefined method `_ragel_parse' for Date:Class (NoMethodError)
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract/schema_definitions.rb:211:in `fallback_string_to_time'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract/schema_definitions.rb:139:in `string_to_time'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/mysql2-0.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:69:in `type_cast'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract/schema_definitions.rb:114:in `extract_default'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/mysql2-0.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:36:in `extract_default'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/activerecord-3.0.7/lib/active_record/connection_adapters/abstract/schema_definitions.rb:34:in `initialize'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/mysql2-0.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:464:in `new'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/mysql2-0.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:464:in `columns'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/mysql2-0.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:463:in `each'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/mysql2-0.2.7/lib/active_record/connection_adapters/mysql2_adapter.rb:463:in `columns'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/arel-2.0.9/lib/arel/table.rb:97:in `columns'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/arel-2.0.9/lib/arel/table.rb:104:in `[]'
```

Trying to run with home_run cmd:

home_run /Users/inspire/newap/lib/benchmarks.rb  
    /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/home_run-1.0.2/bin/home_run:87:in `exec': Exec format error - /Users/inspire/newap/lib/benchmarks.rb (Errno::ENOEXEC)
    from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/home_run-1.0.2/bin/home_run:87
    from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/bin/home_run:19:in`load'
    from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/bin/home_run:19

Another error when I did home_run --uninstall but still had in gemfile:

```
/Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/activesupport-3.0.7/lib/active_support/core_ext/date/calculations.rb:9: undefined method `>>' for class `Date' (NameError)
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/activesupport-3.0.7/lib/active_support/ruby/shim.rb:12:in `require'
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/activesupport-3.0.7/lib/active_support/ruby/shim.rb:12
from /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/actionpack-3.0.7/lib/abstract_controller.rb:6:in `require'
```

**Comment by jeremyevans** [comment]
Bunch of different errors here:

1) `_parse': undefined method`_ragel_parse' for Date:Class: It's probably loading the regular Date class first, then the home_run Date class, but without requiring the date_ext.  Why that's happening, I don't know.  Could be bundler related, especially since the file causing that is /Users/inspire/.rvm/gems/ree-1.8.7-2011.03@newap/gems/home_run-1.0.0/lib/date/format.rb, which is in the gem folder and not the site_ruby directory where home_run --install copies the file too.  You could try uninstalling the gem after running home_run --install, or completely replacing the stdlib date class by copying the home_run files over the stdlib ones.

2) home_run /Users/inspire/newap/lib/benchmarks.rb: This fails because that file is not executable.  Use home_run ruby /Users/inspire/newap/lib/benchmarks.rb.

3) undefined method `>>' for class`Date': This could also be due to a partially loaded date class, or a bug in ActiveSupport that I think is fixed in edge but they didn't backport to 3.0-stable.

**Comment by inspire22** [comment]
Thanks!

2) I'd tried chmod u+x, but I didn't have a #!/usr/bin/env ruby line, which explains that.

3) I'll try again @ next rails release.

Sounds like rails has something similar to this coming or included already (switch hitter?) how much better is this one?

**Comment by jeremyevans** [comment]
It's not in rails, but is is in ruby-head and will be in ruby 1.9.3.  switch_hitter is a better library than home_run.  It's significantly more compatible and almost as fast.  I think in the current state, the only area where home_run is significantly better is that it has a C version of Date._parse using Ragel that works for some formats.  However, I'm guessing that tadf (ruby Date library author) will be working on a faster version of Date._parse before 1.9.3.
